import prisma from "../config/prisma.js";

//helper for verifying edit access
const verifyWriteAccess = async(userId,tripId)=>{
    const member = await prisma.tripMember.findUnique({
        where:{
            trip_id_user_id:{
                trip_id:tripId,
                user_id:userId
            }
        }
    });
    if (!member || member.role === 'VIEWER') throw new Error("NOT_AUTHORIZED_LOGISTICS");
    return true;
};

//1. create an item

export const addPackingItem = async(userId,tripId,itemName,autoGeneratedReason = null)=>{
    await verifyWriteAccess(userId,tripId);//check if the user has permission to modify the trip's logistics (only ADMIN and EDITOR can)

    return await prisma.packingList.create({
        data:{
            trip_id: tripId,
            item_name: itemName,
            auto_generated_reason: autoGeneratedReason
        }
    });
};


//2. read the packing list for a trip
export const getPackingList = async(userId,tripId)=>{
    const member = await prisma.tripMember.findUnique({
        where:{
            trip_id_user_id:{
                trip_id: tripId,
                user_id: userId
            }
        }
    });
    if (!member) throw new Error("NOT_A_MEMBER");

    return await prisma.packingList.findMany({
        where:{
            trip_id: tripId,
        },
        orderBy:{
            is_packed: 'asc',//unpacked items first
        }
    });
};

//3. update an item (mark as packed/unpacked)
export const updatePackingItem = async(userId,tripId,itemId,isPacked,newItemName)=>{
    await verifyWriteAccess(userId,tripId);

    //tenant isolation check
    const existingItem = await prisma.packingList.findFirst({
        where:{
            id:itemId,
            trip_id: tripId
        }
    });
    if(!existingItem){
        throw new Error("ITEM_NOT_FOUND");
    }


    return await prisma.packingList.update({
        where:{
            id:itemId
        },
        data:{
            is_packed:isPacked,
            item_name: newItemName
        }
    });
};

//4. delete an item
export const removePackingItem = async(userId,tripId,itemId)=>{
    await verifyWriteAccess(userId,tripId);

    //tenant isolation check, delete only if item belongs to trip
    return await prisma.packingList.deleteMany({
        where:{
            id:itemId,
            trip_id: tripId
        }
    });
};